const QPREFIX = '@@questions';

export const GET_QUESTIONS = `${QPREFIX}/GET_QUESTIONS`;
export const GET_QUESTIONS_SUCCESS = `${QPREFIX}/GET_QUESTIONS_SUCCESS`;
export const GET_QUESTIONS_ERROR = `${QPREFIX}/GET_QUESTIONS_ERROR`;

const CPREFIX = '@@count';
export const COUNT_SCORE = `${CPREFIX}/COUNT_SCORE`;
